/// Generated by json-dart-serializable plugin.
/// When some incorrect data generated, please fix it.
/// Finally, run flutter build_runner auto generate *.g.dart file.
import 'package:json_annotation/json_annotation.dart';

part 'hot_search_model.g.dart';

/// Github content
@JsonSerializable()
class HotSearchModel {
  int index;
  String content;
  String url;

  /// Constructor...
  HotSearchModel({
    required this.index,
    required this.content,
    required this.url,
  });

  /// Deserializer...
  factory HotSearchModel.fromJson(Map<String, dynamic> json) => _$HotSearchModelFromJson(json);

  /// Serializer...
  Map<String, dynamic> toJson() => _$HotSearchModelToJson(this);
}
