/// Generated by json-dart-serializable plugin.
/// When some incorrect data generated, please fix it.
/// Finally, run flutter build_runner auto generate *.g.dart file.
import 'package:json_annotation/json_annotation.dart';

part 'github_label.g.dart';

/// labels
@JsonSerializable()
class GithubLabel {
  /// id
  int id;

  /// node_id
  @JsonKey(name: 'node_id')
  String nodeId;

  /// url
  String url;

  /// name
  String name;

  /// color
  String color;

  /// default
  @JsonKey(name: 'default')
  bool isDefault;

  /// description
  String description;

  /// Constructor...
  GithubLabel({
    required this.id,
    required this.nodeId,
    required this.url,
    required this.name,
    required this.color,
    required this.isDefault,
    required this.description,
  });

  /// Deserializer...
  factory GithubLabel.fromJson(Map<String, dynamic> json) => _$GithubLabelFromJson(json);

  /// Serializer...
  Map<String, dynamic> toJson() => _$GithubLabelToJson(this);
}
