/// Generated by json-dart-serializable plugin.
/// When some incorrect data generated, please fix it.
/// Finally, run flutter build_runner auto generate *.g.dart file.
import 'package:cw2bit/infrastructure/api/github/models/github_enum.dart';
import 'package:json_annotation/json_annotation.dart';

part 'github_content.g.dart';

/// Github content
@JsonSerializable()
class GithubContent {
  /// name
  String name;

  /// path
  String path;

  /// sha
  String sha;

  /// size
  int size;

  /// url
  String url;

  /// html_url
  @JsonKey(name: 'html_url')
  String htmlUrl;

  /// git_url
  @JsonKey(name: 'git_url')
  String gitUrl;

  /// download_url
  @JsonKey(name: 'download_url')
  String? downloadUrl;

  /// type
  @GithubContentTypeConverter()
  GithubContentTypeEnum type;

  /// content
  String? content;

  /// encoding
  String? encoding;

  /// Constructor...
  GithubContent({
    required this.name,
    required this.path,
    required this.sha,
    required this.size,
    required this.url,
    required this.htmlUrl,
    required this.gitUrl,
    this.downloadUrl,
    required this.type,
    this.content,
    this.encoding,
  });

  /// Deserializer...
  factory GithubContent.fromJson(Map<String, dynamic> json) => _$GithubContentFromJson(json);

  /// Serializer...
  Map<String, dynamic> toJson() => _$GithubContentToJson(this);
}
