/// Generated by json-dart-serializable plugin.
/// When some incorrect data generated, please fix it.
/// Finally, run flutter build_runner auto generate *.g.dart file.
import 'package:cw2bit/infrastructure/api/github/models/issues/github_user.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:qkit/qkit.dart';

part 'github_comment.g.dart';

/// 评论
@JsonSerializable(explicitToJson: true)
class GithubComment {
  /// id
  int id;

  /// node_id
  @JsonKey(name: 'node_id')
  String nodeId;

  /// url
  String url;

  /// html_url
  @JsonKey(name: 'html_url')
  String htmlUrl;

  /// body
  String body;

  /// user
  GithubUser user;

  /// created_at
  @JsonKey(name: 'created_at')
  @YYYY_MM_dd_T_HH_mm_ss_Z_DateTimeConverter()
  DateTime createdAt;

  /// updated_at
  @JsonKey(name: 'updated_at')
  @YYYY_MM_dd_T_HH_mm_ss_Z_DateTimeConverter()
  DateTime updatedAt;

  /// issue_url
  @JsonKey(name: 'issue_url')
  String issueUrl;

  /// author_association
  @JsonKey(name: 'author_association')
  String authorAssociation;

  /// Constructor...
  GithubComment({
    required this.id,
    required this.nodeId,
    required this.url,
    required this.htmlUrl,
    required this.body,
    required this.user,
    required this.createdAt,
    required this.updatedAt,
    required this.issueUrl,
    required this.authorAssociation,
  });

  /// Deserializer...
  factory GithubComment.fromJson(Map<String, dynamic> json) => _$GithubCommentFromJson(json);

  /// Serializer...
  Map<String, dynamic> toJson() => _$GithubCommentToJson(this);
}
