name: qkit
description: "core tiny framework."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flustars_flutter3: ^3.0.0
  decimal: ^2.3.3
  rational: ^2.2.2
  sp_util: ^2.0.3
  # 事件总线 https://code.makery.ch/library/dart-event-bus/
  event_bus: ^2.0.0
  # 状态管理，路由管理 https://github.com/jonataslaw/getx
  get: ^4.6.5
  # pojo <-> json处理：https://pub.dev/packages/json_serializable
  # json注解使用：https://github.com/google/json_serializable.dart/blob/master/example/lib/example.dart
  json_annotation: ^4.6.0
  # 权限处理 https://github.com/baseflow/flutter-permission-handler
  permission_handler: ^10.2.0
  # 设备网络连接状态 https://plus.fluttercommunity.dev/
  connectivity_plus: ^2.3.5
  # 设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: ^9.1.0
  # 应用包信息 https://plus.fluttercommunity.dev/
  package_info_plus: ^4.2.0
  # 设备网络信息 https://plus.fluttercommunity.dev/
  network_info_plus: ^4.1.0
  # 网络库，相关插件见https://github.com/flutterchina/dio/blob/master/README-ZH.md
  # https://github.com/flutterchina/dio
  dio: ^4.0.6
  # 应用路径处理，例如临时目录、应用内部文件路径
  path_provider: ^2.1.3
  # 数字展示处理 https://github.com/entronad/number_display
  number_display: ^3.0.0
  # 资源处理插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^6.2.1
  # uuid https://github.com/Daegalus/dart-uuid
  uuid: ^3.0.6
  # 日志 https://github.com/SourceHorizon/logger
  logger: ^2.0.2+1
  # svg图片处理 https://github.com/dnfield/flutter_svg
  flutter_svg: ^2.0.9
  # 简易使用loading加载 https://github.com/nslogx/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # 下拉、上拉加载 https://github.com/xxzj990-game/flutter_pulltorefresh
  pull_to_refresh_flutter3: ^2.0.2
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.2.1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.3.1
  # dialog https://github.com/mono0926/adaptive_dialog
  adaptive_dialog: ^1.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # json序列化/反序列化代码生成处理器
  json_serializable: 6.3.1
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: any #^2.1.11

# dart脚本运行IDE插件
scripts:
  build_runner_build: flutter packages pub run build_runner build --delete-conflicting-outputs

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
