# 自动打包参考：https://github.com/LeetaoGoooo/discussion-blog/discussions/53
# main.yml
# 自动构建 Apk
name: Build and Release apk

# 工作流程触发的时机，手动触发
# https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflow
on:
  workflow_dispatch:

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v2
      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          # Java版本问题：androidx/annotation/experimental/lint/ExperimentalIssueRegistry has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
          # 解决方法：https://www.baeldung.com/java-lang-unsupportedclassversion
          java-version: "17.x"
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.22.3"
      # 下载项目依赖
      - run: flutter pub get
      - run: echo $ENCODED_KEYSTORE | base64 -di > android/app/cw2bit.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
      # 打包 APK
      - run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
      # 获取发布时间
      - name: Get current date
        id: date
        run: | 
          echo "{date}={$(date +'%Y-%m-%dT%H:%M')}" >> $GITHUB_STATE
      # 发布到 Release
      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          name: 1bit-R-${{ env.date }}
          tag: 1bit
          token: ${{ secrets.RELEASE_TOKEN }}
